[package]
name = "sorrow-reactive"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "sorrow_reactive"

[dependencies]
leptos_reactive = "0.2.5"