[workspace]
members = ["crates/*"]

[package]
name = "sorrow-rs"
authors = ["shoftee"]
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "sorrow"
path = "src/lib.rs"

[[bin]]
name = "engine"
path = "src/bin/engine.rs"

[[bin]]
name = "ui"
path = "src/bin/ui.rs"

[dependencies]
sorrow-derive = { path = "crates/derive" }
sorrow-reactive = { path = "crates/reactive" }
leptos = "0.2.5"
gloo-worker = "0.2"
leptos_meta = { version = "0.2.5", features = ["csr"] }
wasm-bindgen = "0.2.84"
serde = "1.0.162"
gloo-timers = "0.2.6"
time = { version = "0.3.21", features = ["wasm-bindgen"] }
