[package]
name = "sorrow-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "sorrow"
path = "src/lib.rs"

[[bin]]
name = "engine"
path = "src/bin/engine.rs"

[[bin]]
name = "ui"
path = "src/bin/ui.rs"

[dependencies]
leptos = "0.2.5"
gloo-worker = "0.2"
leptos_meta = { version = "0.2.5", features = ["csr"] }
wasm-bindgen = "0.2.84"
serde = "1.0.162"
leptos_reactive = "0.2.5"
