[package]
name = "sorrow-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = "0.2.5"
leptos_meta = { version = "0.2.5", features = ["csr"] }
wasm-bindgen = "0.2.84"
